extends Node

var global_node_map = {
	"NetworkGameUDPENetPeerModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"NetworkENetServerManager": {"path_tree": "Manager/NetworkENetServerManager", "type": "Node"},
		"NetworkChannelManager": {"path_tree": "Manager/NetworkChannelManager", "type": "Node"},
		"Map": {"path_tree": "Map", "type": "Node"},
		"ChannelMap": {"path_tree": "Manager/NetworkChannelManager/Map/ChannelMap", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"NetworkPacketManager": {"path_tree": "Manager/NetworkPacketManager", "type": "Node"},
		"PacketDispatchHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketDispatchHandler", "type": "Node"},
		"PacketProcessingHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketProcessingHandler", "type": "Node"},
		"PacketCreationHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketCreationHandler", "type": "Node"},
		"PacketHashHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketHashHandler", "type": "Node"},
		"PacketCacheHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketCacheHandler", "type": "Node"},
		"PacketConverterHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketConverterHandler", "type": "Node"},
		"PacketValidationHandler": {"path_tree": "Manager/NetworkPacketManager/Handler/PacketValidationHandler", "type": "Node"},
		"NetworkHandler": {"path_tree": "NetworkHandler", "type": "Node"},
		"GameCore": {"path_tree": "NetworkHandler/GameCore", "type": "Node"},
		"CoreHeartbeatHandler": {"path_tree": "NetworkHandler/GameCore/CoreHeartbeatHandler", "type": "Node"},
		"CoreConnectionHandler": {"path_tree": "NetworkHandler/GameCore/CoreConnectionHandler", "type": "Node"},
		"CoreDisconnectionHandler": {"path_tree": "NetworkHandler/GameCore/CoreDisconnectionHandler", "type": "Node"},
		"CorePingHandler": {"path_tree": "NetworkHandler/GameCore/CorePingHandler", "type": "Node"},
		"CoreServerStatusHandler": {"path_tree": "NetworkHandler/GameCore/CoreServerStatusHandler", "type": "Node"},
		"CoreErrorHandler": {"path_tree": "NetworkHandler/GameCore/CoreErrorHandler", "type": "Node"},
		"GameMovement": {"path_tree": "NetworkHandler/GameMovement", "type": "Node"},
		"MovementPlayerHandler": {"path_tree": "NetworkHandler/GameMovement/MovementPlayerHandler", "type": "Node"},
		"MovementPlayerSyncHandler": {"path_tree": "NetworkHandler/GameMovement/MovementPlayerSyncHandler", "type": "Node"},
		"GameInstance": {"path_tree": "NetworkHandler/GameInstance", "type": "Node"},
		"SceneInstanceDataHandler": {"path_tree": "NetworkHandler/GameInstance/SceneInstanceDataHandler", "type": "Node"},
		"GameTrigger": {"path_tree": "NetworkHandler/GameTrigger", "type": "Node"},
		"TriggerEntryHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerEntryHandler", "type": "Node"},
		"TriggerExitHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerExitHandler", "type": "Node"},
		"TriggerInstanceChangeHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerInstanceChangeHandler", "type": "Node"},
		"TriggerZoneChangeHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerZoneChangeHandler", "type": "Node"},
		"TriggerRoomChangeHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerRoomChangeHandler", "type": "Node"},
		"TriggerEventHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerEventHandler", "type": "Node"},
		"TriggerTrapHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerTrapHandler", "type": "Node"},
		"TriggerObjectiveHandler": {"path_tree": "NetworkHandler/GameTrigger/TriggerObjectiveHandler", "type": "Node"},
		"GameUser": {"path_tree": "NetworkHandler/GameUser", "type": "Node"},
		"UserLoginHandler": {"path_tree": "NetworkHandler/GameUser/UserLoginHandler", "type": "Node"},
		"UserTokenHandler": {"path_tree": "NetworkHandler/GameUser/UserTokenHandler", "type": "Node"},
		"GameCharacter": {"path_tree": "NetworkHandler/GameCharacter", "type": "Node"},
		"CharacterFetchHandler": {"path_tree": "NetworkHandler/GameCharacter/CharacterFetchHandler", "type": "Node"},
		"CharacterSelectHandler": {"path_tree": "NetworkHandler/GameCharacter/CharacterSelectHandler", "type": "Node"},
		"CharacterUpdateHandler": {"path_tree": "NetworkHandler/GameCharacter/CharacterUpdateHandler", "type": "Node"},
		"Config": {"path_tree": "Config", "type": "Node"},
	},
	"NetworkDatabaseMongoDBRESTModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"NetworkMiddlewareManager": {"path_tree": "Manager/NetworkMiddlewareManager", "type": "Node"},
		"NetworkEndpointManager": {"path_tree": "Manager/NetworkEndpointManager", "type": "Node"},
		"NetworkHandler": {"path_tree": "NetworkHandler", "type": "Node"},
		"DatabaseServer": {"path_tree": "NetworkHandler/DatabaseServer", "type": "Node"},
		"DatabaseServerAuthHandler": {"path_tree": "NetworkHandler/DatabaseServer/DatabaseServerAuthHandler", "type": "Node"},
		"DatabaseUser": {"path_tree": "NetworkHandler/DatabaseUser", "type": "Node"},
		"DatabaseUserLoginHandler": {"path_tree": "NetworkHandler/DatabaseUser/DatabaseUserLoginHandler", "type": "Node"},
		"DatabaseUserTokenHandler": {"path_tree": "NetworkHandler/DatabaseUser/DatabaseUserTokenHandler", "type": "Node"},
		"DatabaseCharacter": {"path_tree": "NetworkHandler/DatabaseCharacter", "type": "Node"},
		"DatabaseCharacterFetchHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterFetchHandler", "type": "Node"},
		"DatabaseCharacterSelectHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterSelectHandler", "type": "Node"},
		"DatabaseCharacterUpdateHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterUpdateHandler", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"Config": {"path_tree": "Config", "type": "Node"},
		"Map": {"path_tree": "Map", "type": "Node"},
	},
	"NetworkDatabaseGodotWebsocketModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"NetworkMiddlewareManager": {"path_tree": "Manager/NetworkMiddlewareManager", "type": "Node"},
		"NetworkEndpointManager": {"path_tree": "Manager/NetworkEndpointManager", "type": "Node"},
		"NetworkHandler": {"path_tree": "NetworkHandler", "type": "Node"},
		"DatabaseServer": {"path_tree": "NetworkHandler/DatabaseServer", "type": "Node"},
		"DatabaseServerAuthHandler": {"path_tree": "NetworkHandler/DatabaseServer/DatabaseServerAuthHandler", "type": "Node"},
		"DatabaseUser": {"path_tree": "NetworkHandler/DatabaseUser", "type": "Node"},
		"DatabaseUserLoginHandler": {"path_tree": "NetworkHandler/DatabaseUser/DatabaseUserLoginHandler", "type": "Node"},
		"DatabaseUserTokenHandler": {"path_tree": "NetworkHandler/DatabaseUser/DatabaseUserTokenHandler", "type": "Node"},
		"DatabaseCharacter": {"path_tree": "NetworkHandler/DatabaseCharacter", "type": "Node"},
		"DatabaseCharacterFetchHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterFetchHandler", "type": "Node"},
		"DatabaseCharacterSelectHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterSelectHandler", "type": "Node"},
		"DatabaseCharacterUpdateHandler": {"path_tree": "NetworkHandler/DatabaseCharacter/DatabaseCharacterUpdateHandler", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"Config": {"path_tree": "Config", "type": "Node"},
		"Map": {"path_tree": "Map", "type": "Node"},
	},
	"ServerConsole": {
		"ServerConsoleContainer": {"path_tree": "ServerConsoleContainer", "type": "VBoxContainer"},
		"PlaceHolderTop": {"path_tree": "ServerConsoleContainer/PlaceHolderTop/PlaceHolderTop", "type": "Label"},
		"TopStartServer": {"path_tree": "ServerConsoleContainer/TopStartServer", "type": "HBoxContainer"},
		"ServerLabel": {"path_tree": "ServerConsoleContainer/TopStartServer/ServerLabel", "type": "Label"},
		"ServerPresetList": {"path_tree": "ServerConsoleContainer/TopStartServer/ServerPresetList", "type": "ItemList"},
		"StartServerButton": {"path_tree": "ServerConsoleContainer/TopStartServer/StartServerButton", "type": "Button"},
		"StopServerButton": {"path_tree": "ServerConsoleContainer/TopStartServer/StopServerButton", "type": "Button"},
		"ServerPortLabel": {"path_tree": "ServerConsoleContainer/TopStartServer/ServerPortLabel", "type": "Label"},
		"ServerPortInput": {"path_tree": "ServerConsoleContainer/TopStartServer/ServerPortInput", "type": "LineEdit"},
		"ServerAutoStartCheckButton": {"path_tree": "ServerConsoleContainer/TopStartServer/ServerAutoStartCheckButton", "type": "CheckButton"},
		"UseDatabaseLabel": {"path_tree": "ServerConsoleContainer/TopStartServer/UseDatabaseLabel", "type": "Label"},
		"UseDatabaseTypeLabel": {"path_tree": "ServerConsoleContainer/TopStartServer/UseDatabaseTypeLabel", "type": "Label"},
		"TopBackend": {"path_tree": "ServerConsoleContainer/TopBackend", "type": "HBoxContainer"},
		"BackendIP": {"path_tree": "ServerConsoleContainer/TopBackend/BackendIP", "type": "Label"},
		"BackendIPInput": {"path_tree": "ServerConsoleContainer/TopBackend/BackendIPInput", "type": "LineEdit"},
		"BackendPortLabel": {"path_tree": "ServerConsoleContainer/TopBackend/BackendPortLabel", "type": "Label"},
		"BackendPortInput": {"path_tree": "ServerConsoleContainer/TopBackend/BackendPortInput", "type": "LineEdit"},
		"ServerValidationToken": {"path_tree": "ServerConsoleContainer/TopBackend/ServerValidationToken", "type": "Label"},
		"ServerValidationTokenInput": {"path_tree": "ServerConsoleContainer/TopBackend/ServerValidationTokenInput", "type": "LineEdit"},
		"ConnectToBackend": {"path_tree": "ServerConsoleContainer/TopBackend/ConnectToBackend", "type": "Button"},
		"DisconnectFromBackend": {"path_tree": "ServerConsoleContainer/TopBackend/DisconnectFromBackend", "type": "Button"},
		"Mid": {"path_tree": "ServerConsoleContainer/Mid", "type": "HBoxContainer"},
		"SideContainer": {"path_tree": "ServerConsoleContainer/Mid/SideContainer", "type": "VBoxContainer"},
		"PlayerListLabel": {"path_tree": "ServerConsoleContainer/Mid/SideContainer/PlayerListLabel", "type": "Label"},
		"PlayerContainer": {"path_tree": "ServerConsoleContainer/Mid/SideContainer/PlayerContainer", "type": "VBoxContainer"},
		"PlayerContainerPanel": {"path_tree": "ServerConsoleContainer/Mid/SideContainer/PlayerContainer/PlayerContainerPanel", "type": "Panel"},
		"PlayerListManager": {"path_tree": "ServerConsoleContainer/Mid/SideContainer/PlayerContainer/PlayerContainerPanel/PlayerListManager", "type": "ItemList"},
		"PlayerVisualMonitorPanel": {"path_tree": "ServerConsoleContainer/Mid/SideContainer/PlayerContainer/PlayerVisualMonitorPanel", "type": "Panel"},
		"ControlContainer": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer", "type": "VBoxContainer"},
		"ServerControlPanelLabel": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanelLabel", "type": "Label"},
		"ServerControlPanel": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel", "type": "Panel"},
		"ServerControlGridContainer": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer", "type": "GridContainer"},
		"NetworkContainer": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/NetworkContainer", "type": "GridContainer"},
		"Network": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/NetworkContainer/Network", "type": "Label"},
		"PlayerControlsButton": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/PlayerControlsButton", "type": "GridContainer"},
		"Player": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/PlayerControlsButton/Player", "type": "Label"},
		"Kick": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/PlayerControlsButton/Kick", "type": "Button"},
		"Ban": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/PlayerControlsButton/Ban", "type": "Button"},
		"Watch": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/PlayerControlsButton/Watch", "type": "Button"},
		"Container3": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/Container3", "type": "GridContainer"},
		"Label": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/Container4/Label", "type": "Label"},
		"Button": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/Container3/Button", "type": "Button"},
		"Button2": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/ServerControlPanel/ServerControlGridContainer/Container3/Button2", "type": "Button"},
		"Button3": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/Button3", "type": "Button"},
		"Button4": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/Button4", "type": "Button"},
		"Button5": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/Button5", "type": "Button"},
		"Button6": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/Button6", "type": "Button"},
		"Container4": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/Container4", "type": "GridContainer"},
		"FeaturesList": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/Container4/FeaturesList", "type": "ItemList"},
		"BackendButtonPanelLabel": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanelLabel", "type": "Label"},
		"BackendButtonPanel": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel", "type": "Panel"},
		"GridContainer": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer", "type": "GridContainer"},
		"Container1": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/Container1", "type": "GridContainer"},
		"LevelControlPanel": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/LevelControlPanel", "type": "Label"},
		"GenerateButton": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/GenerateButton", "type": "Button"},
		"ViewLevelButton": {"path_tree": "ServerConsoleContainer/Mid/ControlContainer/BackendButtonPanel/GridContainer/LevelControlPanel/ViewLevelButton", "type": "Button"},
		"ConsoleContainer": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer", "type": "VBoxContainer"},
		"ServerClientPanelLabel": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerClientPanelLabel", "type": "Label"},
		"ServerClientPanel": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerClientPanel", "type": "Panel"},
		"ServerLog": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerClientPanel/ServerLog", "type": "RichTextLabel"},
		"ServerBackendPanelLabel": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerBackendPanelLabel", "type": "Label"},
		"ServerBackendPanel": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerBackendPanel", "type": "Panel"},
		"ServerBackendLog": {"path_tree": "ServerConsoleContainer/Mid/ConsoleContainer/ServerBackendPanel/ServerBackendLog", "type": "RichTextLabel"},
		"Bottom": {"path_tree": "ServerConsoleContainer/Bottom", "type": "HBoxContainer"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"ServerConsoleLifeCycleHandler": {"path_tree": "Handler/ServerConsoleLifeCycleHandler", "type": "Node"},
		"ServerConsolePresetHandler": {"path_tree": "Handler/ServerConsolePresetHandler", "type": "Node"},
		"ServerConsoleSettingsHandler": {"path_tree": "Handler/ServerConsoleSettingsHandler", "type": "Node"},
		"ServerConsoleUILoadHandler": {"path_tree": "Handler/ServerConsoleUILoadHandler", "type": "Node"},
	},
	"UserSessionModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"UserSessionManager": {"path_tree": "Manager/UserSessionManager", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"SessionLockHandler": {"path_tree": "Manager/UserSessionManager/Handler/SessionLockHandler", "type": "Node"},
		"TimeoutHandler": {"path_tree": "Manager/UserSessionManager/Handler/TimeoutHandler", "type": "Node"},
		"SessionLockTypeHandler": {"path_tree": "Manager/UserSessionManager/Handler/SessionLockTypeHandler", "type": "Node"},
	},
	"builder": {
		"VBoxContainer": {"path_tree": "VBoxContainer", "type": "VBoxContainer"},
	},
	"CoreTree": {
		"ServerManager": {"path_tree": "ServerManager", "type": "Node"},
		"PlayerMovementData": {"path_tree": "ServerManager/PlayerMovementData", "type": "Node"},
		"Handler": {"path_tree": "ServerManager/PlayerVisualMonitor/Handler", "type": "Node"},
		"PlayerVisualMonitor": {"path_tree": "ServerManager/PlayerVisualMonitor", "type": "Node"},
		"AudioManager": {"path_tree": "AudioManager", "type": "Node"},
		"Utils": {"path_tree": "Utils", "type": "Node"},
	},
	"LoadingScene": {
		"Panel": {"path_tree": "Panel", "type": "Panel"},
		"VBoxContainer": {"path_tree": "Panel/VBoxContainer/HBoxContainer5/VBoxContainer", "type": "VBoxContainer"},
		"HBoxContainer": {"path_tree": "Panel/VBoxContainer/HBoxContainer", "type": "HBoxContainer"},
		"Label": {"path_tree": "Panel/VBoxContainer/HBoxContainer5/VBoxContainer3/Label", "type": "Label"},
		"HBoxContainer2": {"path_tree": "Panel/VBoxContainer/HBoxContainer2", "type": "HBoxContainer"},
		"VBoxContainer2": {"path_tree": "Panel/VBoxContainer/HBoxContainer5/VBoxContainer2", "type": "VBoxContainer"},
		"Label2": {"path_tree": "Panel/VBoxContainer/HBoxContainer2/VBoxContainer3/Label2", "type": "Label"},
		"VBoxContainer3": {"path_tree": "Panel/VBoxContainer/HBoxContainer5/VBoxContainer3", "type": "VBoxContainer"},
		"HBoxContainer3": {"path_tree": "Panel/VBoxContainer/HBoxContainer3", "type": "HBoxContainer"},
		"TextureRect": {"path_tree": "Panel/VBoxContainer/HBoxContainer3/TextureRect", "type": "TextureRect"},
		"HBoxContainer4": {"path_tree": "Panel/VBoxContainer/HBoxContainer4", "type": "HBoxContainer"},
		"ProgressBar": {"path_tree": "Panel/VBoxContainer/HBoxContainer4/ProgressBar", "type": "ProgressBar"},
		"HBoxContainer5": {"path_tree": "Panel/VBoxContainer/HBoxContainer5", "type": "HBoxContainer"},
		"NetworkHandler": {"path_tree": "NetworkHandler", "type": "Node"},
		"InstanceDataHandler": {"path_tree": "NetworkHandler/InstanceDataHandler", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"PlaceHolderHandler": {"path_tree": "Handler/PlaceHolderHandler", "type": "Node"},
		"PlaceHolderHandler2": {"path_tree": "Handler/PlaceHolderHandler2", "type": "Node"},
		"InputHandler": {"path_tree": "Handler/InputHandler", "type": "Node"},
	},
	"GameWorldModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"InstanceManager": {"path_tree": "Manager/InstanceManager", "type": "Node"},
		"Handler": {"path_tree": "Manager/TriggerManager/Handler", "type": "Node"},
		"InstanceLifecycleHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceLifecycleHandler", "type": "Node"},
		"InstanceSceneManager": {"path_tree": "Manager/InstanceManager/Handler/InstanceSceneManager", "type": "Node"},
		"InstanceCreationHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceCreationHandler", "type": "Node"},
		"InstanceCacheHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceCacheHandler", "type": "Node"},
		"InstanceAssignmentHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceAssignmentHandler", "type": "Node"},
		"InstanceDestructionHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceDestructionHandler", "type": "Node"},
		"InstanceBoundaryHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceBoundaryHandler", "type": "Node"},
		"InstanceLoaderHandler": {"path_tree": "Manager/InstanceManager/Handler/InstanceLoaderHandler", "type": "Node"},
		"InstancePlayerCharacterHandler": {"path_tree": "Manager/InstanceManager/Handler/InstancePlayerCharacterHandler", "type": "Node"},
		"ChunkManager": {"path_tree": "Manager/ChunkManager", "type": "Node"},
		"ChunkLifecycleHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkLifecycleHandler", "type": "Node"},
		"ChunkSceneManager": {"path_tree": "Manager/ChunkManager/Handler/ChunkSceneManager", "type": "Node"},
		"ChunkCreationHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkCreationHandler", "type": "Node"},
		"ChunkCacheHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkCacheHandler", "type": "Node"},
		"ChunkAssignmentHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkAssignmentHandler", "type": "Node"},
		"ChunkDestructionHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkDestructionHandler", "type": "Node"},
		"ChunkBoundaryHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkBoundaryHandler", "type": "Node"},
		"ChunkEventHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkEventHandler", "type": "Node"},
		"ChunkLoaderHandler": {"path_tree": "Manager/ChunkManager/Handler/ChunkLoaderHandler", "type": "Node"},
		"TriggerManager": {"path_tree": "Manager/TriggerManager", "type": "Node"},
		"TriggerInstanceChangeHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerInstanceChangeHandler", "type": "Node"},
		"TriggerZoneChangeHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerZoneChangeHandler", "type": "Node"},
		"TriggerRoomChangeHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerRoomChangeHandler", "type": "Node"},
		"TriggerEventHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerEventHandler", "type": "Node"},
		"TriggerTrapHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerTrapHandler", "type": "Node"},
		"TriggerObjectiveHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerObjectiveHandler", "type": "Node"},
		"TriggerArea2DCalculationHandler": {"path_tree": "Manager/TriggerManager/Handler/TriggerArea2DCalculationHandler", "type": "Node"},
		"SpawnPointManager": {"path_tree": "Manager/SpawnPointManager", "type": "Node"},
	},
	"GameLevelModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"LevelManager": {"path_tree": "Manager/LevelManager", "type": "Node"},
		"Handler": {"path_tree": "Manager/LevelManager/Handler", "type": "Node"},
		"LevelCreationHandler": {"path_tree": "Manager/LevelManager/Handler/LevelCreationHandler", "type": "Node"},
		"LevelSaveHandler": {"path_tree": "Manager/LevelManager/Handler/LevelSaveHandler", "type": "Node"},
		"LevelMapGenerator": {"path_tree": "Manager/LevelManager/Handler/LevelMapGenerator", "type": "Node"},
	},
	"GamePlayerModule": {
		"Manager": {"path_tree": "Manager", "type": "Node"},
		"PlayerManager": {"path_tree": "Manager/PlayerManager", "type": "Node"},
		"Handler": {"path_tree": "Handler", "type": "Node"},
		"PlayerSpawnHandler": {"path_tree": "Manager/PlayerManager/Handler/PlayerSpawnHandler", "type": "Node"},
		"PlayerMovementManager": {"path_tree": "Manager/PlayerMovementManager", "type": "Node"},
		"PlayerMovementData": {"path_tree": "Manager/PlayerMovementData", "type": "Node"},
		"PlayerVisualMonitor": {"path_tree": "Manager/PlayerVisualMonitor", "type": "Node"},
		"CharacterManager": {"path_tree": "Manager/CharacterManager", "type": "Node"},
	},
}
